# Generated by Django 5.1.4 on 2024-12-15 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0003_quality_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('process', models.CharField(choices=[('SRT', 'Stress Relief Treatment'), ('CL', 'Cleaning'), ('MP', 'Procedure'), ('PT', 'Post Treatment')], default='MP', max_length=50)),
                ('description', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_publish', to=settings.AUTH_USER_MODEL)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_requirement', to='specifications.spec')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='specificati_title_25950a_idx')],
            },
        ),
    ]
