# Generated by Django 5.1.4 on 2024-12-15 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0005_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='spec',
        ),
        migrations.AddField(
            model_name='requirement',
            name='classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spec_requirement', to='specifications.classification'),
            preserve_default=False,
        ),
    ]
