# Generated by Django 5.1.4 on 2024-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0007_alter_classification_options_alter_quality_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['manual_title'], 'verbose_name_plural': 'Manual Process'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['title'], 'verbose_name_plural': 'Process Method'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'ordering': ['name'], 'verbose_name_plural': 'quality requirements'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['tank_identification'], 'verbose_name_plural': 'Tank Process'},
        ),
        migrations.AlterModelOptions(
            name='spec',
            options={'ordering': ['-title'], 'verbose_name_plural': 'specification'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='classes',
            field=models.CharField(default='Class N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='method',
            field=models.CharField(default='Method N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='types',
            field=models.CharField(default='Type N/A', max_length=50),
        ),
    ]
