# Generated by Django 5.1.4 on 2024-12-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0008_alter_manual_options_alter_method_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='tank_size',
        ),
        migrations.AddField(
            model_name='solution',
            name='is_rectified',
            field=models.BooleanField(default=False),
        ),
    ]
