# Generated by Django 5.1.4 on 2024-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0009_remove_solution_tank_size_solution_is_rectified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='temp_min',
        ),
        migrations.AddField(
            model_name='solution',
            name='temp_range',
            field=models.CharField(default='Ambient', help_text='Temperature in F', max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='tank_contents',
            field=models.CharField(help_text='Chemical Contents', max_length=200),
        ),
    ]
