# Generated by Django 5.1.4 on 2024-12-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0011_remove_classification_classes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='classificiation',
            new_name='classification',
        ),
    ]
