# Generated by Django 5.1.4 on 2024-12-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0012_rename_classificiation_classification_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
