# Generated by Django 5.1.4 on 2024-12-15 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0013_delete_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('process_identity', models.CharField(choices=[('CR', 'Chrome Plate'), ('NI', 'Nickel Plate'), ('CD', 'Cadmium Plate'), ('AN', 'Anodize'), ('CF', 'Chemical Converision'), ('PA', 'Passivation'), ('ST', 'Coating Strip'), ('BR', 'Brush Plate'), ('PR', 'Prepen Etch'), ('TE', 'Temper Etch')], default='N/A', max_length=50)),
                ('description', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_publish', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_class', to='specifications.classification')),
            ],
            options={
                'verbose_name_plural': 'Process Method',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.AddIndex(
            model_name='processrequired',
            index=models.Index(fields=['title'], name='specificati_title_33b015_idx'),
        ),
    ]
